### ISSUE TITLE
No prompting for "cloud data" in tutorial

### ISSUE THREAD

**Issue by brian-swan** [Microsoft/TouchDevelop#116]
The tutorial engine will not prompt for **cloud data**. Example here: http://tdev.ly/cfhlc.

**Comment by mmoskal** [comment]
It works for me, maybe an issue with skill levels?

**Comment by brian-swan** [comment]
I'm following it in "coder" level. What level did you follow it in?

**Comment by brian-swan** [comment]
Just so you don't think I'm crazy: 
![clouddata](https://cloud.githubusercontent.com/assets/918682/6989890/55b2a0a8-da16-11e4-83b6-0540f3e5151f.PNG)

**Comment by mmoskal** [comment]
Yeah, **cloud data** seems gone in *coder*. Peli?

**Comment by pelikhan** [comment]
fixed in 4377c13d7c132c5b0f7a370d0c740ce6ee5c43b2

**Comment by brian-swan** [comment]
I'm finding that this is still an issue in the **coder** level. i.e. When in **coder** level, I'm still not prompted for **cloud data** and the tutorial comes to a stop. I *am*, however, correctly prompted in **expert** mode.
